/* Generated by Cloud 4 Sonnet */

// Data storage
let bugDates = JSON.parse(localStorage.getItem('bugDates')) || [];
let startDate = localStorage.getItem('startDate') || new Date().toISOString().split('T')[0];

// Calendar state
let currentViewDate = new Date();

// Initialize the app
function init() {
  console.log('Initializing Stress Tracker...');
  updateDaysCounter();
  renderCalendar();
  updateStats();
}

// Update the main days counter
function updateDaysCounter() {
  const today = new Date();
  const lastBugDate = bugDates.length > 0 ? 
      new Date(Math.max(...bugDates.map(date => new Date(date)))) : 
      new Date(startDate);
    
  const timeDiff = today - lastBugDate;
  const daysDiff = Math.floor(timeDiff / (1000 * 60 * 60 * 24));
    
  document.getElementById('daysCounter').textContent = daysDiff;
}

// Report a bug (reset counter)
function reportBug() {
  showUpdateNotification('Are you sure you want to report a stress? This will reset your streak.', () => {
    const today = new Date().toISOString().split('T')[0];
    if (!bugDates.includes(today)) {
      bugDates.push(today);
      localStorage.setItem('bugDates', JSON.stringify(bugDates));
    }
    updateDaysCounter();
    renderCalendar();
    updateStats();
  });
}

// Calendar navigation
function previousMonth() {
  currentViewDate.setMonth(currentViewDate.getMonth() - 1);
  renderCalendar();
}

function nextMonth() {
  currentViewDate.setMonth(currentViewDate.getMonth() + 1);
  renderCalendar();
}

// Render calendar
function renderCalendar() {
  const year = currentViewDate.getFullYear();
  const month = currentViewDate.getMonth();
    
  // Update calendar title
  const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'];
  document.getElementById('calendarTitle').textContent = `${monthNames[month]} ${year}`;
  
  // Clear calendar
  const grid = document.getElementById('calendarGrid');
  grid.innerHTML = '';
    
  // Add day headers
  const dayHeaders = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  dayHeaders.forEach(day => {
    const header = document.createElement('div');
    header.className = 'calendar-day-header';
    header.textContent = day;
    grid.appendChild(header);
  });
  
  // Get first day of month and number of days
  const firstDay = new Date(year, month, 1);
  const lastDay = new Date(year, month + 1, 0);
  const daysInMonth = lastDay.getDate();
  const startingDayOfWeek = firstDay.getDay();
  
  // Add empty cells for previous month
  const prevMonth = new Date(year, month, 0);
  const daysInPrevMonth = prevMonth.getDate();
  
  for (let i = startingDayOfWeek - 1; i >= 0; i--) {
    const day = daysInPrevMonth - i;
    const dayElement = createDayElement(day, true, year, month - 1);
    grid.appendChild(dayElement);
  }
  
  // Add days of current month
  for (let day = 1; day <= daysInMonth; day++) {
    const dayElement = createDayElement(day, false, year, month);
    grid.appendChild(dayElement);
  }
  
  // Add days from next month to fill the grid
  const totalCells = grid.children.length - 7; // Subtract header row
  const remainingCells = 42 - totalCells; // 6 weeks * 7 days
  
  for (let day = 1; day <= remainingCells; day++) {
    const dayElement = createDayElement(day, true, year, month + 1);
    grid.appendChild(dayElement);
  }
}

// Create a day element
function createDayElement(day, isOtherMonth, year, month) {
  const dayElement = document.createElement('div');
  dayElement.className = 'calendar-day';
  dayElement.textContent = day;
    
  if (isOtherMonth) {
      dayElement.classList.add('other-month');
  }
    
  // Check if this is today
  const today = new Date();
  const dayDate = new Date(year, month, day);
  if (!isOtherMonth && 
      dayDate.toDateString() === today.toDateString()) {
      dayElement.classList.add('today');
  }
    
  // Check if this day has a bug
  const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  if (bugDates.includes(dateString)) {
      dayElement.classList.add('bug-day');
  }
    
  return dayElement;
}

// Update statistics
function updateStats() {
  // Total bugs
  document.getElementById('totalBugs').textContent = bugDates.length;
    
  // Longest streak
  const longestStreak = calculateLongestStreak();
  document.getElementById('longestStreak').textContent = longestStreak;
    
  // Bugs this month
  const currentMonth = new Date().getMonth();
  const currentYear = new Date().getFullYear();
  const bugsThisMonth = bugDates.filter(date => {
      const bugDate = new Date(date);
      return bugDate.getMonth() === currentMonth && bugDate.getFullYear() === currentYear;
  }).length;
  document.getElementById('currentMonth').textContent = bugsThisMonth;
}

// Calculate longest streak
function calculateLongestStreak() {
  if (bugDates.length === 0) {
    const today = new Date();
    const start = new Date(startDate);
    return Math.floor((today - start) / (1000 * 60 * 60 * 24));
  }
    
  // Sort bug dates
  const sortedDates = bugDates.map(date => new Date(date)).sort((a, b) => a - b);
  
  let longestStreak = 0;
  let currentStreak = 0;
    
  // Calculate streak from start to first bug
  const firstBug = sortedDates[0];
  const start = new Date(startDate);
  longestStreak = Math.floor((firstBug - start) / (1000 * 60 * 60 * 24));
    
  // Calculate streaks between bugs
  for (let i = 1; i < sortedDates.length; i++) {
    const timeDiff = sortedDates[i] - sortedDates[i - 1];
    const daysDiff = Math.floor(timeDiff / (1000 * 60 * 60 * 24)) - 1;
    longestStreak = Math.max(longestStreak, daysDiff);
  }
    
  // Current streak from last bug to today
  if (sortedDates.length > 0) {
    const lastBug = sortedDates[sortedDates.length - 1];
    const today = new Date();
    const currentStreak = Math.floor((today - lastBug) / (1000 * 60 * 60 * 24));
    longestStreak = Math.max(longestStreak, currentStreak);
  }
    
  return longestStreak;
}

function showToast(message) {
    const toast = document.getElementById('toast');
    toast.textContent = message;
    toast.classList.add('show');
    setTimeout(() => {
        toast.classList.remove('show');
    }, 2000);
}

function showUpdateNotification(textMessage, confirmFunction) {
  const notification = document.getElementById('updateNotification');
  const updateBtn = document.getElementById('updateBtn');
  const dismissBtn = document.getElementById('dismissBtn');
  const messageSpan = document.getElementsByClassName('update-message');

  if (messageSpan && messageSpan.length > 0) {
    messageSpan[0].textContent = textMessage;
  }

  notification.classList.add('show');

  const yesFunction = confirmFunction || (() => {
    window.location.reload();
  });

  updateBtn.addEventListener('click', () => {
    yesFunction();
    window.location.reload();
  });

  dismissBtn.addEventListener('click', () => {
    notification.classList.remove('show');
  });
}

window.reportBug = reportBug;
window.previousMonth = previousMonth;
window.nextMonth = nextMonth;

// Initialize when page loads
document.addEventListener('DOMContentLoaded', init);

// PWA Update handling
if ('serviceWorker' in navigator) {
  let updateAvailable = false;

  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js', { scope: '/' }).then(registration => {
      registration.addEventListener('updatefound', () => {
        const newWorker = registration.installing;

        newWorker.addEventListener('statechange', () => {
          if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
            // New service worker installed, show update notification
            updateAvailable = true;
            showUpdateNotification('New version available! Update?');
          }
        });
      });
    });
  });
}
